import os
import re

from ..health.health_rules import SKIP_DIRS, SOURCE_EXTENSIONS, is_test_path
from .context_schema import normalize_file_context


GENERATED_HEADER_RE = re.compile(r"\b(generated by|auto[- ]generated|do not edit)\b", re.I)


def _relative(root, path):
    return os.path.relpath(path, root).replace("\\", "/")


def _iter_candidate_files(repo_path):
    root = os.path.abspath(repo_path)
    for current, dirs, files in os.walk(root):
        dirs[:] = [
            name
            for name in dirs
            if name not in SKIP_DIRS and not name.startswith(".reposense_") and name not in {"analysis_runs", ".mypy_cache"}
        ]
        for name in files:
            if os.path.splitext(name)[1].lower() in SOURCE_EXTENSIONS:
                yield _relative(root, os.path.join(current, name))


def _first_source_line(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            lines = handle.read().splitlines()
    except OSError:
        return 0, "", ""
    header = "\n".join(lines[:20])
    for index, line in enumerate(lines, 1):
        if line.strip():
            return index, line.strip()[:500], header
    return 0, "", header


def _path_parts(file_path):
    normalized = "/" + str(file_path or "").replace("\\", "/").lower().strip("/") + "/"
    return normalized, {part for part in normalized.split("/") if part}


def classify_file_context(repo_path, file_path):
    normalized, parts = _path_parts(file_path)
    file_name = str(file_path or "").replace("\\", "/").rsplit("/", 1)[-1]
    absolute = os.path.join(os.path.abspath(repo_path), str(file_path).replace("/", os.sep))
    line, snippet, header = _first_source_line(absolute)
    signals = []
    limitations = []

    if GENERATED_HEADER_RE.search(header) or {"generated", "gen"} & parts:
        context = "generated"
        confidence = 0.98 if GENERATED_HEADER_RE.search(header) else 0.92
        modifier = "exclude_from_primary_review"
        signals.append("generated_header" if GENERATED_HEADER_RE.search(header) else "generated_path")
    elif {"seed", "seeds", "seeder", "seeders"} & parts or re.search(
        r"(^|[._-])seed(er)?([._-]|$)", file_name, re.I
    ):
        context = "seed"
        confidence = 0.95
        modifier = "downweight"
        signals.append("seed_path")
    elif {"templates", "template", "scaffolds", "scaffold", ".hygen", "_templates"} & parts or ".template." in normalized:
        context = "template"
        confidence = 0.95
        modifier = "downweight"
        signals.append("template_path")
    elif {"fixture", "fixtures"} & parts:
        context = "fixture"
        confidence = 0.95
        modifier = "downweight"
        signals.append("fixture_path")
    elif is_test_path(str(file_path)):
        context = "test"
        confidence = 0.95
        modifier = "downweight"
        signals.append("test_path")
    elif {"migrations", "migration", "alembic", "flyway", "liquibase"} & parts:
        context = "migration"
        confidence = 0.9
        modifier = "normal"
        signals.append("migration_path")
    elif {"src", "app", "lib", "service", "services", "controller", "controllers", "domain"} & parts:
        context = "production"
        confidence = 0.82
        modifier = "normal"
        signals.append("production_source_path")
    else:
        context = "unknown"
        confidence = 0.4
        modifier = "normal"
        signals.append("file_context_unresolved")
        limitations.append("file_context_unresolved")

    evidence = []
    if line >= 1:
        evidence.append(
            {
                "source_type": "file_context",
                "file": str(file_path).replace("\\", "/"),
                "start_line": line,
                "end_line": line,
                "snippet": snippet or os.path.basename(str(file_path)),
            }
        )
    else:
        limitations.append("source_location_unavailable")
    return normalize_file_context(
        {
            "file": file_path,
            "context": context,
            "confidence": confidence,
            "signals": signals,
            "evidence_refs": evidence,
            "review_modifier": modifier,
            "limitations": limitations,
        }
    )


def classify_file_contexts(repo_path, extra_paths=None):
    files = set(_iter_candidate_files(repo_path))
    files.update(str(path).replace("\\", "/") for path in (extra_paths or []) if str(path or ""))
    annotations = [classify_file_context(repo_path, file_path) for file_path in sorted(files)]
    annotations.sort(key=lambda row: (row["file"], row["annotation_id"]))
    return annotations


def apply_file_context(findings, annotations):
    by_file = {row.get("file"): row for row in annotations or []}
    calibrated = []
    for finding in findings or []:
        row = dict(finding)
        annotation = by_file.get(str(row.get("file") or "").replace("\\", "/"))
        if not annotation:
            calibrated.append(row)
            continue
        metadata = dict(row.get("metadata") or {})
        context = annotation["context"]
        rule_id = str(row.get("rule_id") or "")
        effective_modifier = annotation["review_modifier"]
        limitations = list(metadata.get("limitations") or [])

        if context == "generated":
            if rule_id == "CHD-004":
                row["severity"] = "low"
                row["status"] = "suspected"
                effective_modifier = "downweight"
            else:
                row["severity"] = "low"
                effective_modifier = "exclude_from_primary_review"
            limitations.append("non_production_file_context")
        elif context in {"seed", "template", "fixture", "test"}:
            if rule_id == "CHD-005":
                row["severity"] = "low"
                row["status"] = "suspected"
                effective_modifier = "exclude_from_primary_review"
            elif rule_id in {"CHD-001", "CHD-002", "CHD-003", "CHD-004"}:
                row["severity"] = "low"
                effective_modifier = "downweight"
                if rule_id == "CHD-004":
                    row["status"] = "suspected"
            limitations.append("non_production_file_context")

        metadata.update(
            {
                "file_context": context,
                "context_confidence": annotation["confidence"],
                "review_modifier": effective_modifier,
                "context_reason": ", ".join(annotation["signals"]),
                "context_annotation_id": annotation["annotation_id"],
                "limitations": sorted(set(limitations)),
            }
        )
        row["metadata"] = metadata
        calibrated.append(row)
    return calibrated
