import os
import shutil
import subprocess
import unittest

from tests._tmpdir import make_temp_dir


class DemoRunSmokeTest(unittest.TestCase):
    def test_demo_run_generates_required_artifacts(self):
        out_root = make_temp_dir(prefix="reposense_demo_smoke_")
        try:
            if os.name == "nt":
                cmd = [
                    "powershell",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-File",
                    "tools/demo_run.ps1",
                    "-Out",
                    out_root,
                    "-Repo",
                    "tests/fixtures/repos/java_api_queue_db_closure_min",
                ]
                env = None
            else:
                cmd = [
                    "bash",
                    "scripts/demo_run.sh",
                ]
                env = os.environ.copy()
                env["OUT"] = out_root
            p = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=900,
                cwd=os.getcwd(),
                env=env,
            )
            self.assertEqual(
                p.returncode,
                0,
                msg=(
                    "stdout:\n"
                    + p.stdout.decode("utf-8", errors="ignore")
                    + "\n\nstderr:\n"
                    + p.stderr.decode("utf-8", errors="ignore")
                ),
            )

            run_dirs = [
                os.path.join(out_root, n)
                for n in os.listdir(out_root)
                if n.startswith("run-") and os.path.isdir(os.path.join(out_root, n))
            ]
            self.assertTrue(run_dirs, "no run-* directory generated by demo_run.ps1")
            run_dir = sorted(run_dirs)[-1]

            self.assertTrue(os.path.isfile(os.path.join(run_dir, "report.html")))
            self.assertTrue(os.path.isfile(os.path.join(run_dir, "learn", "index.html")))
            self.assertTrue(os.path.isfile(os.path.join(run_dir, "patterns.json")))
            self.assertTrue(os.path.isfile(os.path.join(run_dir, "ai_summary.md")))
            self.assertTrue(os.path.isfile(os.path.join(run_dir, "ai_risks", "risks.md")))
            self.assertTrue(os.path.isfile(os.path.join(run_dir, "run_manifest.json")))

            explain_root = os.path.join(run_dir, "ai_explain")
            explain_md = []
            if os.path.isdir(explain_root):
                for root, _, files in os.walk(explain_root):
                    if "explain.md" in files:
                        explain_md.append(os.path.join(root, "explain.md"))
            self.assertTrue(explain_md, "no ai_explain/*/explain.md generated")
        finally:
            shutil.rmtree(out_root, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
